[package]
name = "testcase-buildx-cache"
version = "0.1.0"
authors = ["Peter Holak <peter@holak.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
